package com.example.cloudtable.Database.generator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tablesDaoConfig;

    private final TablesDao tablesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tablesDaoConfig = daoConfigMap.get(TablesDao.class).clone();
        tablesDaoConfig.initIdentityScope(type);

        tablesDao = new TablesDao(tablesDaoConfig, this);

        registerDao(Tables.class, tablesDao);
    }
    
    public void clear() {
        tablesDaoConfig.getIdentityScope().clear();
    }

    public TablesDao getTablesDao() {
        return tablesDao;
    }

}
