package com.example.cloudtable.Database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TABLES".
 */
public class Tables {

    private Integer table_id;
    private String table_name;
    private Integer table_left;
    private Integer table_top;
    private Integer table_right;
    private Integer table_bottom;

    public Tables() {
    }

    public Tables(Integer table_id, String table_name, Integer table_left, Integer table_top, Integer table_right, Integer table_bottom) {
        this.table_id = table_id;
        this.table_name = table_name;
        this.table_left = table_left;
        this.table_top = table_top;
        this.table_right = table_right;
        this.table_bottom = table_bottom;
    }

    public Integer getTable_id() {
        return table_id;
    }

    public void setTable_id(Integer table_id) {
        this.table_id = table_id;
    }

    public String getTable_name() {
        return table_name;
    }

    public void setTable_name(String table_name) {
        this.table_name = table_name;
    }

    public Integer getTable_left() {
        return table_left;
    }

    public void setTable_left(Integer table_left) {
        this.table_left = table_left;
    }

    public Integer getTable_top() {
        return table_top;
    }

    public void setTable_top(Integer table_top) {
        this.table_top = table_top;
    }

    public Integer getTable_right() {
        return table_right;
    }

    public void setTable_right(Integer table_right) {
        this.table_right = table_right;
    }

    public Integer getTable_bottom() {
        return table_bottom;
    }

    public void setTable_bottom(Integer table_bottom) {
        this.table_bottom = table_bottom;
    }

}
